 -  test_name: "DotNet_Config_Validate"
    dockerfile_lines: 
      - ADD https://download.newrelic.com/dot_net_agent/latest_release/NewRelicDotNetAgent_x64.msi NewRelicDotNetAgent_x64.msi
      - RUN ["msiexec.exe", "/i", "NewRelicDotNetAgent_x64.msi" ,"/qb", "NR_LICENSE_KEY=LICENSE-KEY-HERE", "INSTALLLEVEL=1"]
    log_entry_expected: 
     - Success.*DotNet/Config/Agent
    log_entry_not_expected: 
     - Success.*(Ruby|Java|Node|Python|Infra)/Config/Agent
     - Failure.*DotNet/Config/Agent