name: Rollback

on:
  release:
    types: [deleted]

jobs:
  rollback:
    runs-on: ubuntu-latest
    steps:
      - name: fetch latest release
        uses: thebritican/fetch-latest-release@v1
        id: flr
        with:
          github_token: ${{ github.token }}
      - name: delete latest release tag
        shell: bash
        run: |
            echo "deleting tag associated with latest release:"
            echo ${{ steps.flr.outputs.tag_name }}
            git push --delete origin ${{ steps.flr.outputs.tag_name }}
      - name: Debug data around fetch-latest-release
        run: echo {{ steps.flr.outputs }}
      - name: remove nrdiag zip files from download.newrelic.com related to last release
        shell: bash
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run : |
            set -e
            CURRENT=$(cat releaseVersion.txt | awk -F'currentReleaseVersion=' '{printf$2}')
            CURRENTZIP="nrdiag_${CURRENT}.zip"
            echo "my currentzip:"
            echo nrdiag_${CURRENT}.zip
            echo $CURRENTZIP
            PREV=$(cat releaseVersion.txt | awk -F'prevReleaseVersion=' '{printf$2}')
            PREVZIP="nrdiag_${PREV}.zip"
            echo "my prevzip:"
            echo nrdiag_${PREV}.zip
            aws s3 rm s3://${{ secrets.S3_BUCKET }}/nrdiag/test/${CURRENTZIP}
            echo "current release was removed"
            aws s3 cp s3://${{ secrets.S3_BUCKET }}/nrdiag/test/${PREVZIP} s3://${{ secrets.S3_BUCKET }}/nrdiag/test/nrdiag_latest.zip
            echo "previous release is now latest zip"
            echo ${PREV} >> version.txt
            aws s3 cp version.txt s3://${{ secrets.S3_BUCKET }}/nrdiag/test/version.txt



