 -  test_name: DotNet_CustomInstrumentation_Collect
    docker_from: base-dotnet-framework
    dockerfile_lines: 
      - COPY ["/fixtures/dotnet/root/ProgramData/New Relic/.NET Agent/Extensions/customInstrumentationFile.xml", "c:/ProgramData/New Relic/.NET Agent/Extensions/customInstrumentationFile.xml"]
    log_entry_expected: 
     - Success.*DotNet/CustomInstrumentation/Collect
    log_entry_not_expected: 
     - Failure.*DotNet/CustomInstrumentation/Collect

 -  test_name: DotNet_CustomInstrumentation_Collect_No_Files
    docker_from: base-dotnet-framework
    dockerfile_lines: 
    docker_cmd: ./nrdiag_x64 -filter all
    log_entry_expected:  
      - None.*DotNet/CustomInstrumentation/Collect
    log_entry_not_expected:
      - Failure.*DotNet/CustomInstrumentation/Collect
      - Success.*DotNet/CustomInstrumentation/Collect
